version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pipster-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pipster_identity_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pipster-network

volumes:
  postgres_data:
    driver: local

networks:
  pipster-network:
    driver: bridge